apiVersion: v1
kind: Pod
metadata:
  name: my-iscsi-pod
spec:
  restartPolicy: Always
  containers:
  - name: my-iscsi-pod
    image: nginx
    volumeMounts:
      - name: iscsi-test
        mountPath: /mnt
  volumes:
  - name: iscsi-test
    iscsi:
      targetPortal: 192.168.1.98:3260
      iqn: iqn.2022-07.net.strokov.storage-k8s:disk1
      fsType: ext4
      lun: 0
      readOnly: false
