apiVersion: v1
kind: Pod 
metadata:
  name: storage-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: storage-pvc
  containers:
    - name: task-pv-container
      image: kubernetes/pause
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
