apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  storageClassName: "iscsi-targetd-vg-targetd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
