---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
    - name: iscsipd-ro
      image: kubernetes/pause
      volumeMounts:
        - mountPath: "/data"
          name: iscsivol
  volumes:
    - name: iscsivol
      iscsi:
        targetPortal: 192.168.1.98
        iqn: iqn.2022-07.net.strokov.storage-k8s:disk2
        lun: 0
        fsType: ext4
        readOnly: false
        chapAuthDiscovery: false
        chapAuthSession: false
