apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    tier: payment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  selector:
    matchLabels:
      tier: payment
  template:
    metadata:
      labels:
        app: payment
        tier: payment
    spec:
      containers:
        - name: server
          image: pstrokov/hipster-paymentservice:v0.0.2
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
            - name: DISABLE_DEBUGGER
              value: "1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
